CREATE TABLE `username_classlist` (
    TODAY   INT(50) PRIMARY KEY,
    class1 VARCHAR(255),
    class2 VARCHAR(255),
    class3 VARCHAR(255),
    class4 VARCHAR(255),
    class5 VARCHAR(255),
    class6 VARCHAR(255),
    class7 VARCHAR(255),
    class8 VARCHAR(255),
    class9 VARCHAR(255),
    class10 VARCHAR(255),
    class11 VARCHAR(255),
    class12 VARCHAR(255),
    class13 VARCHAR(255),
    class14 VARCHAR(255),
    class15 VARCHAR(255)
);

INSERT INTO `username_classlist` VALUES(1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `username_classlist` VALUES(2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `username_classlist` VALUES(3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `username_classlist` VALUES(4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `username_classlist` VALUES(5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `username_classlist` VALUES(6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `username_classlist` VALUES(7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
